# SPDX-License-Identifier: Apache-2.0

CONFIG_SERIAL=n
CONFIG_UART_CONSOLE=n

CONFIG_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_BOOT_BANNER=y
CONFIG_TLSR8258_RTT_CONSOLE=y

CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYS_CLOCK_EXISTS=y
CONFIG_TLSR8258_STIMER=y
CONFIG_GPIO=y
