CONFIG_MAIN_STACK_SIZE=2048
CONFIG_HEAP_MEM_POOL_SIZE=0
CONFIG_BOOT_BANNER=n
CONFIG_PRINTK=n
CONFIG_SERIAL=n
CONFIG_UART_CONSOLE=n
CONFIG_SYS_CLOCK_EXISTS=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_LOG=n
CONFIG_MBEDTLS=n
CONFIG_TC32_BOOT_MIRROR_SIZE=0x8000
CONFIG_TLSR8258_FLASH_HANG_REPRO_MODE_DIRECT=y
