CONFIG_NETWORKING=y
CONFIG_NET_L2_ETHERNET=n
CONFIG_NET_L2_IEEE802154=y
CONFIG_NET_IPV4=n
CONFIG_NET_IPV6=n
CONFIG_NET_UDP=n
CONFIG_NET_TCP=n
CONFIG_NET_SOCKETS=n
CONFIG_ETH_DRIVER=n
CONFIG_ETH_NATIVE_TAP=n

CONFIG_ZIGBEE=y
CONFIG_ZIGBEE_ED=y
CONFIG_ZIGBEE_CHANNEL=11
CONFIG_ZIGBEE_BDB=y
CONFIG_ZIGBEE_ZCL=y
CONFIG_ZIGBEE_GP=n
CONFIG_ZIGBEE_OTA=n
CONFIG_ZIGBEE_WWAH=n
CONFIG_ZIGBEE_MAC_TRX_STUBS=n

CONFIG_IEEE802154=y
CONFIG_IEEE802154_RAW_MODE=y
CONFIG_IEEE802154_NATIVE_SIM_SOCKET=y
CONFIG_IEEE802154_NATIVE_SIM_SOCKET_RX_STACK_SIZE=2048
CONFIG_IEEE802154_NATIVE_SIM_SOCKET_RX_THREAD_PRIO=2

CONFIG_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_SERIAL=n
CONFIG_UART_CONSOLE=n
CONFIG_LOG=n

CONFIG_NVS=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y

CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_NET_BUF_RX_COUNT=4
CONFIG_NET_BUF_TX_COUNT=4
