/* SPDX-License-Identifier: Apache-2.0 */
/* Based on Telink tl_zigbee_sdk/proj/common/compiler.h (Apache 2.0) */
#pragma once

#include <zephyr/toolchain.h>

#define _attribute_packed_          __packed
#define _attribute_aligned_(n)      __aligned(n)
#define _attribute_session_(s)      /* no-op on Zephyr */
/*
 * Vendor placed timing-critical helpers (CCA, RSSI poll, current-tick read)
 * in RAM to avoid flash wait-states. On this Zephyr port the cross-section
 * thunks generated by the TC32 LLVM linker for .ramfunc callees wedge the
 * thread on the first cross-region call from .text. Fall back to keeping
 * these functions in regular .text — the Zephyr 802.15.4 driver handles
 * CSMA-CA itself, so the residual vendor MAC TRX timing margin is moot.
 */
#define _attribute_ram_code_        /* no-op on Zephyr TC32 port */
#define _attribute_no_inline_       __attribute__((noinline))
#define _attribute_always_inline_   __attribute__((always_inline)) static inline
#define _attribute_data_retention_  /* no-op */
#define _attribute_custom_code_     /* no-op */
#define _attribute_gpio_wakeup_     /* no-op */

/* SDK code-section attributes — no-op on Zephyr (linker script handles placement) */
#define _CODE_APS_
#define _CODE_BDB_
#define _CODE_ZCL_
#define _CODE_NWK_
#define _CODE_ZDO_
#define _CODE_AF_
#define _CODE_SS_
#define _CODE_GP_
#define _CODE_MAC_

/* Some vendor headers reference u_int8_t */
#ifndef u_int8_t
typedef unsigned char u_int8_t;
#endif
